[package]
name = "ice-party-watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
thiserror = "1"
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.25"
anyhow = "1"
public-ip = "0.2.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.11", features = ["fmt", "ansi", "tracing-log", "std", "env-filter"] }
tracing-bunyan-formatter = "0.3.4"
gcp_auth = "0.7.4"
secrecy = "0.8"
reqwest = "0.11"
aws-config = "0.55.1"
aws-sdk-route53 = "0.26.0"
